/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticationRegistrationRouteImport } from './routes/authentication/registration'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as AuthenticationForgotRouteImport } from './routes/authentication/forgot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRegistrationRoute =
  AuthenticationRegistrationRouteImport.update({
    id: '/authentication/registration',
    path: '/authentication/registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationForgotRoute = AuthenticationForgotRouteImport.update({
  id: '/authentication/forgot',
  path: '/authentication/forgot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/registration': typeof AuthenticationRegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/registration': typeof AuthenticationRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/registration': typeof AuthenticationRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication/forgot'
    | '/authentication/login'
    | '/authentication/registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/forgot'
    | '/authentication/login'
    | '/authentication/registration'
  id:
    | '__root__'
    | '/'
    | '/authentication/forgot'
    | '/authentication/login'
    | '/authentication/registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationForgotRoute: typeof AuthenticationForgotRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationRegistrationRoute: typeof AuthenticationRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/registration': {
      id: '/authentication/registration'
      path: '/authentication/registration'
      fullPath: '/authentication/registration'
      preLoaderRoute: typeof AuthenticationRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot': {
      id: '/authentication/forgot'
      path: '/authentication/forgot'
      fullPath: '/authentication/forgot'
      preLoaderRoute: typeof AuthenticationForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationForgotRoute: AuthenticationForgotRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationRegistrationRoute: AuthenticationRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
